apiVersion: v1
kind: Service
metadata:
  name: data-retrieval-microservice
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5001
    port: 5001
    nodePort: 30001
 selector:
  app: python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-retrieval-microservice
spec:
  selector:
    matchLabels:
      app: python
  replicas: 3
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: data-retrieval-microservice
        imagePullPolicy: Always
        image: iuwitcher2020/dockerized_data_retrieval
        ports:
        - containerPort: 5001
